package org.saul.dto;

/**
* Generated by some old goat.  A JSON DTO has no setters.
*/
public class ${className}{

    <#-- add class property definitions. -->
    <#list fields as p>
    private ${p.javaTypeName} ${p.propertyName};
    </#list>

    <#-- add class getters. -->
    <#list fields as p>
    public ${p.javaTypeName} ${p.getterName}(){
        return this.${p.propertyName};
    }

    </#list>
}
