package org.saul.dto;

/**
* Generated by some old goat.
*/
public class ${className}{

    <#-- add class property definitions. -->
    <#list classProperties as p>
    private ${p.javaType} ${p.propertyName}
    </#list>

    <#-- add class getters. -->
    <#list classProperties as p>
    public ${p.javaType} ${p.getterName}(){
        return this.${p.propertyName};
    }

    </#list>
    <#-- add class setters. -->
    <#list classProperties as p>

	public ${className} ${p.setterName}( ${p.javaType} ${p.inName} ){
		this.${p.propertyName} = ${p.inName};
        return this;
	}
    </#list>
}
